import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Homebody from '../Components/Homebody.js'
import Navbar from '../Components/Navbar'
import Landing from '../Components/Landing.js'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Narma</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="manifest" href="/manifest.json" />
        <link rel="apple-touch-icon" href="/vercel.svg"></link>
       
        <meta name="theme-color" content="#fff" />
      </Head>
      <Navbar/>
      <Landing/>

    </div>
  )
}
